agents:
  execution:
    enabled: true
    max_retry_attempts: 3
    slippage_tolerance: 0.1
  risk_management:
    enabled: true
    max_drawdown: 15
    var_confidence: 0.95
  technical_analysis:
    enabled: true
    indicators:
    - RSI
    - MACD
    - Bollinger
    timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
binance:
  rate_limit:
    orders_per_second: 10
    requests_per_minute: 1200
  testnet: true
database:
  backup_enabled: true
  duckdb_path: ./data/development/market_data.duckdb
  pool_size: 10
  url: sqlite:///./data/development/trading.db
environment: development
logging:
  backup_count: 5
  file_enabled: true
  file_path: ./logs/development.log
  level: DEBUG
  max_file_size: 10MB
monitoring:
  alert_thresholds:
    cpu_usage: 80
    error_rate: 5
    memory_usage: 85
  enabled: true
  health_check_interval: 30
  metrics_retention_days: 30
trading:
  leverage: 1
  max_daily_loss_percent: 5.0
  max_position_percent: 10.0
  max_position_size: 1000.0
  mode: paper
  stop_loss_percent: 2.0
web:
  cors_enabled: true
  debug: true
  host: 0.0.0.0
  port: 8000
